FROM python:3.9-slim

ENV PIP_NO_CACHE_DIR=off \
PYTHONPATH=/usr/local/src/stock_bot

RUN apt-get update && apt-get install -y --no-install-recommends gcc

WORKDIR /usr/local/src/stock_bot

RUN pip install pipenv 

COPY stock_bot/Pipfile stock_bot/Pipfile.lock ./

RUN pipenv install --system

COPY ./ ./