FROM python:3.9-slim

RUN pip install pipenv

# ENV SRC_DIR /usr/local/src/app

# WORKDIR ${SRC_DIR}

# COPY Pipfile Pipfile.lock ${SRC_DIR}/

# RUN pipenv install --system --clear

# COPY ./ ${SRC_DIR}/
